### PR TITLE
add twitter meta info

### PR DESCRIPTION
**Pull request by robertylewis**
Following what was done for the docs, I think this should work!

### CODE REVIEW

**Comment by robertylewis** [comment]
It occurs to me the image says "mathlib blog" while the blog is called the "community blog." I did this without thinking and because I was basing it on the "mathlib docs" image. It could be changed with some design creativity.

**Review by eric-wieser — APPROVED** [review]
LGTM. Easiest just to merge and check that it works?

**Comment by robertylewis** [comment]
Probably. I don't know if/how often Twitter updates those cards so someone might need to tweet to test it.

**Comment by robertylewis** [comment]
The new card will look a little weird side by side with the docs image, but I think that's the lesser evil -- branding it as the community blog is better.

**Review by bryangingechen — APPROVED** [review]

**Comment by bryangingechen** [comment]
Let's give it a shot! (Who wants to try tweeting a link?)

**Comment by robertylewis** [comment]
It passes the validator: https://cards-dev.twitter.com/validator

**Pull request merged**
